lockonplace: true
enablelogging: true
blacklist:
- DIAMOND
- DIAMOND_AXE
- DIAMOND_BARDING
- DIAMOND_BLOCK
- DIAMOND_BOOTS
- DIAMOND_CHESTPLATE
- DIAMOND_HELMET
- DIAMOND_HOE
- DIAMOND_LEGGINGS
- DIAMOND_ORE
- DIAMOND_PICKAXE
- DIAMOND_SPADE
- DIAMOND_SWORD
- IRON_AXE
- IRON_BARDING
- IRON_BLOCK
- IRON_BOOTS
- IRON_CHESTPLATE
- IRON_DOOR
- IRON_DOOR_BLOCK
- IRON_FENCE
- IRON_HELMET
- IRON_HOE
- IRON_INGOT
- IRON_LEGGINGS
- IRON_ORE
- IRON_PICKAXE
- IRON_PLATE
- IRON_SPADE
- IRON_SWORD
- IRON_TRAPDOOR
- GOLD_AXE
- GOLD_BARDING
- GOLD_BLOCK
- GOLD_BOOTS
- GOLD_CHESTPLATE
- GOLD_HELMET
- GOLD_HOE
- GOLD_INGOT
- GOLD_LEGGINGS
- GOLD_NUGGET
- GOLD_ORE
- GOLD_PICKAXE
- GOLD_PLATE
- GOLD_RECORD
- GOLD_SPADE
- GOLD_SWORD
- GOLDEN_APPLE
- GOLDEN_CARROT
- EMERALD
- EMERALD_BLOCK
- EMERALD_ORE
- NETHER_STAR
- BEACON
- CAULDRON_ITEM
- CHAINMAIL_BOOTS
- CHAINMAIL_CHESTPLATE
- CHAINMAIL_HELMET
- CHAINMAIL_LEGGINGS
- DRAGON_EGG
- ENCHANTMENT_TABLE
- LAVA_BUCKET
- MILK_BUCKET
- MINECART
- MOB_SPAWNER
- MONSTER_EGG
- MONSTER_EGGS
- NAME_TAG
- BUCKET
- RAILS
- SADDLE
- SHEARS
- SKULL_ITEM
- STORAGE_MINECART
- POWERED_MINECART
- COMPASS
- WATCH