lockonplace: true
enablelogging: true
blacklist:
- DIAMOND
- DIAMOND_AXE
- DIAMOND_HORSE_ARMOR
- DIAMOND_BLOCK
- DIAMOND_BOOTS
- DIAMOND_CHESTPLATE
- DIAMOND_HELMET
- DIAMOND_HOE
- DIAMOND_LEGGINGS
- DIAMOND_ORE
- DIAMOND_PICKAXE
- DIAMOND_SHOVEL
- DIAMOND_SWORD
- IRON_AXE
- IRON_HORSE_ARMOR
- IRON_BLOCK
- IRON_BOOTS
- IRON_CHESTPLATE
- IRON_DOOR
- IRON_BARS
- IRON_HELMET
- IRON_HOE
- IRON_INGOT
- IRON_LEGGINGS
- IRON_ORE
- IRON_PICKAXE
- HEAVY_WEIGHTED_PRESSURE_PLATE
- IRON_SHOVEL
- IRON_SWORD
- IRON_TRAPDOOR
- GOLDEN_AXE
- GOLDEN_HORSE_ARMOR
- GOLD_BLOCK
- GOLDEN_BOOTS
- GOLDEN_CHESTPLATE
- GOLDEN_HELMET
- GOLDEN_HOE
- GOLD_INGOT
- GOLDEN_LEGGINGS
- GOLD_NUGGET
- GOLD_ORE
- GOLDEN_PICKAXE
- LIGHT_WEIGHTED_PRESSURE_PLATE
- GOLDEN_SHOVEL
- GOLDEN_SWORD
- GOLDEN_APPLE
- GOLDEN_CARROT
- EMERALD
- EMERALD_BLOCK
- EMERALD_ORE
- NETHER_STAR
- BEACON
- CAULDRON
- CHAINMAIL_BOOTS
- CHAINMAIL_CHESTPLATE
- CHAINMAIL_HELMET
- CHAINMAIL_LEGGINGS
- DRAGON_EGG
- ENCHANTING_TABLE
- LAVA_BUCKET
- MILK_BUCKET
- MINECART
- SPAWNER
- NAME_TAG
- BUCKET
- RAIL
- POWERED_RAIL
- ACTIVATOR_RAIL
- DETECTOR_RAIL
- SADDLE
- SHEARS
- WITHER_SKELETON_SKULL
- SKELETON_SKULL
- ZOMBIE_HEAD
- PLAYER_HEAD
- DRAGON_HEAD
- CREEPER_HEAD
- COMPASS
- WATCH
- TNT_MINECART
- FURNACE_MINECART
- CHEST_MINECART
- TOTEM_OF_UNDYING