name: BasicBarrels
author: basicmark
description: Storage Barrels
main: io.github.basicmark.basicbarrels.BasicBarrels
startup: postworld
url: https://github.com/basicmark/BasicBarrels
depend: []
softdepend: []
version: 1.0
commands:
    barrel:
        description: Type /barrel ? for more info
        usage: /barrel ?
permissions:
    barrel.use:
        description: Create, add items to, remove items from, unlock and break your own barrels
        default: false
    barrel.mod.use_others:
        description: Add items to, remove items from, unlock and break other players barrels
        default: false